### PR TITLE
weather crash fix

### PR DESCRIPTION
**Pull request by m2rtin**
- faulty conversion removed
- added safety block for filling variables with the first record from json by default

### CODE REVIEW

**Comment by tuetschek** [comment]
I still think that this "salvage block" is not needed at all – can you give me a case where it will crash when the block is not there?

If filling in values from the 1st returned point is needed, I would prefer to do it every time, before the `for fc1, fc2` cycle, without the added `if not hasattr`.

**Comment by m2rtin** [comment]
the filling of default values beforehand can be arranged, i agree, but let's sync our minds regarding the crash.

**Comment by tuetschek** [comment]
I'm sorry, I couldn't push into this because it's your personal fork... so, how about changing the "daily" condition to this:

```
        # get prediction
        if daily:  # set time to whatever OpenWeatherMap returns in the timestamp for the 1st day
            date = datetime.combine(date.date(),
                                    datetime.fromtimestamp(input_json['list'][0]['dt']).time())
        # convert the date/time to Unix timestamp (timezone-independent)
        ts = int(date.strftime("%s"))
```

Would this be acceptable for you?

**Comment by m2rtin** [comment]
i like it, i'll insert it!

**Comment by tuetschek** [comment]
it's probably not surprising but i like it now :-). I think that this should work OK.

**Pull request merged**
