### PR TITLE
make ptien slu working

### PR DESCRIPTION
**Pull request by oplatek**
I hit the issue of missing argument (slu cfg) during using Martin Vejman callogs from PTIEN task.
This should fix the issue

### CODE REVIEW

**Comment by jurcicek** [comment]
@tuetschek Can you check that?

**Comment by tuetschek** [comment]
@jurcicek : Yes, it wouldn't work without the additional parameter and the path is correct. 

However, the Czech version manages [without having to use a file path](https://github.com/UFAL-DSG/alex/blob/master/alex/applications/PublicTransportInfoCS/slu/prepare_data.py#L41). It essentially builds the configuration on-the-fly.

I prefer the way the Czech version handles this, but I don't think that this is wrong either. So, it's up to you if you tak it as it is or if you want it to be solved the same way as in the Czech version.

**Comment by jurcicek** [comment]
@oplatek Can you use the solution suggested by @tuetschek ? Thanks!

**Comment by oplatek** [comment]
Done

**Pull request merged**
